#!/bin/bash

red="\e[31m"
green="\e[32m"
yellow="\e[33m"
orange="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
e="\e[0m"


shutt() {
    { "$@" || return $?; } | while read -r line; do
        :
    done
}


initial_update() {
    echo -e "${magenta}Updating local packages${e}"
    sleep 3
    shutt apt update -y 2> /dev/null
    yes|shutt apt upgrade 2> /dev/null
}


downloadytdl() {
    echo -e "${yellow}Setting up required packages${e}"
    pip -qq install -U pip
    pip -qq install -U yt-dlp
    pip -qq install -U spotify-dl
    echo -e "${yellow}Finalizing process${e}"
    curl -o $PREFIX/bin/ytdl -fsSL https://bit.ly/ytdl-advanced
    curl -o $PREFIX/etc/ytdlversion -fsSL https://bit.ly/ytdl-version-advanced
    curl -o ~/bin/termux-url-opener -fsSL https://bit.ly/ytdl-share-advanced
    curl -o ~/bin/ytdl.py -fsSL https://bit.ly/ytdl-py-advanced
    chmod +x $PREFIX/bin/ytdl
    chmod +x ~/bin/termux-url-opener
}


installytdl() {
    initial_update
    echo
    echo -e "${cyan}Allow permission storage${e}"
    echo
    sleep 2
    termux-setup-storage
    shutt pkg install termux-api -y 2> /dev/null
    echo
    echo -e "${cyan}Allow sceeen overlay${e}"
    echo
    sleep 2
    am start --user 0 -a android.settings.action.MANAGE_OVERLAY_PERMISSION -d "package:com.termux"
    echo -e "${orange}Installing Python3${e}"
    shutt pkg install python -y 2> /dev/null
    echo -e "${orange}Installing FFMPEG${e}"
    shutt pkg install ffmpeg -y 2> /dev/null
    downloadytdl
    echo -e "${green}Installation successful${e}"
}


updateytdl() {
    initial_update
    rm $PREFIX/bin/ytdl
    rm $PREFIX/etc/ytdlversion
    rm ~/bin/termux-url-opener
    rm ~/bin/ytdl.py
    downloadytdl
    echo -e "${green}Updated successfully${e}"
}


first_echo() {
    echo -e "${cyan}First time setup may take upto 5 minutes${e}"
    echo -e "${cyan}Depending on your internet speed, may take even longer${e}"
    echo -e "${cyan}${b}Please wait for 2-3 minutes to permit app for file access and screen overlay${e}"
    echo
}


if ! [[ -d ~/bin ]]
then
    mkdir ~/bin
fi


if [[ -f $PREFIX/bin/ytdl ]]
then
    if ! [[ -f $PREFIX/etc/ytdlversion ]]
    then
        rm $PREFIX/bin/ytdl
        first_echo
        installytdl
    else
        v=$(curl -fsSL https://bit.ly/ytdl-version-advanced)
        cv=$(sed -n '1p' $PREFIX/etc/ytdlversion)
        if ! [[ $v == $cv ]]
        then
            updateytdl
        else
            initial_update
            echo -e "${orange}Already Upto Date${e}"
        fi
    fi
else
    first_echo
    installytdl
fi
