#!/bin/bash

if ! [[ -f $PREFIX/bin/spotdl ]]
then
    mv "/sdcard/Download/spotdl" "$PREFIX/bin/spotdl"
    chmod +x "$PREFIX/bin/spotdl"
fi

echo
echo "Checking credentials"

if [[ -f $PREFIX/etc/spotcreds ]]
then
    echo "Credentials found"
    SPOTIFY_CLIENT_ID=$(sed -n '1p' $PREFIX/etc/spotcreds)
    SPOTIFY_CLIENT_SECRET=$(sed -n '2p' $PREFIX/etc/spotcreds)
else
    echo -e "Credentials not found\n\nCreating credentials file\nGet your credentials from https://developer.spotify.com/my-applications"
    echo -e "\nPlease enter Spotify Client ID:\n"
    read SPOTIFY_CLIENT_ID
    echo -e "\n\nPlease enter Spotify Client Secret:\n"
    read SPOTIFY_CLIENT_SECRET
    echo -e "$SPOTIFY_CLIENT_ID\n$SPOTIFY_CLIENT_SECRET" >> $PREFIX/etc/spotcreds
fi

echo
echo  "Please enter the Spotify URL:"
echo

read link

spotify_dl -l $link -s -w -k -o $EXTERNAL_STORAGE/YTDL
