#!/bin/bash


red="\e[31m"
green="\e[32m"
yellow="\e[33m"
orange="\e[34m"
magenta="\e[35m"
cyan="\e[36m"
e="\e[0m"
b="\e[1m"
i="\e[3m"

link=$1

Spotcreds()
{
    echo
    echo -e "${magenta}Checking credentials${e}"
    if [[ -v SPOTIPY_CLIENT_ID ]]
    then
        echo -e "${magenta}Credentials found${e}"
        echo
    else
        echo -e "${red}Credentials not found${e}\n\n${yellow}Creating credentials file\nGet your credentials from${e} ${magenta}https://developer.spotify.com/my-applications${e}"
        echo -e "\n${orange}Please enter Spotify Client ID:\n${e}"
        read CLIENT_ID
        echo -e "\n\n\n${orange}Please enter Spotify Client Secret:\n${e}"
        read CLIENT_SECRET
        echo export SPOTIPY_CLIENT_ID=$CLIENT_ID >> $PREFIX/etc/zshrc
        echo export SPOTIPY_CLIENT_SECRET=$CLIENT_SECRET >> $PREFIX/etc/zshrc
        echo
        echo -e "${green}Credentials saved successfully\nPlease restart app to use this feature{e}"
        exit
    fi
}


Spotdl()
{
    Spotcreds
    spotify_dl -l $link -s -w -k -o $EXTERNAL_STORAGE/YTDL
    exit
}


if [[ $link == *open.spotify.com* ]]
then
    Spotdl
fi


echo
echo -e "${magenta}Do you wish to download Video or Audio?${e}\n\n1. Video\n2. Audio"
echo
read filetype


if [[ $filetype -eq 1 ]]
then
    echo
    echo -e "${magenta}Select your preferred quality${e}\n\n1. Best\n2. High\n3. Medium\n4. Low"
    echo
    read quality
fi


echo
echo -e "${yellow}Working on it\nPlease wait for a while...${e}"
echo
echo


if [[ $filetype -eq 1 ]]
then
    if [[ $quality -eq 1 ]]
    then
        format='(571/402/272/305/337/315/701/401/266/313/304/336/308/700/400/264/271/299/335/303/699/399/137/248/170/298/334/302/698/398/136/247/169/333/697/135/212/244/245/246/397/168/218/219/332/696/134/243/396/167/331/695/133/242/395/330/694/160/278/394)+(328/380338/258/327/256/141/251/bestaudio)'
    elif [[ $quality -eq 2 ]]
    then
        format='(304/336/308/700/400/264/271/299/335/303/699/399/137/248/170/298/334/302/698/398/136/247/169/333/697/135/212/244/245/246/397/168/218/219/332/696/134/243/396/167/331/695/133/242/395/330/694/160/278/394)+(328/380338/258/327/256/141/251/bestaudio)'
    elif [[ $quality -eq 3 ]]
    then
        format='(298/334/302/698/398/136/247/169/333/697/135/212/244/245/246/397/168/218/219/332/696/134/243/396/167/331/695/133/242/395/330/694/160/278/394)+(328/380338/258/327/256/141/251/bestaudio)'
    else
        format='(333/697/135/212/244/245/246/397/168/218/219/332/696/134/243/396/167/331/695/133/242/395/330/694/160/278/394)+(328/380338/258/327/256/141/251/bestaudio)'
    fi
else
    format='328/380338/258/327/256/141/251/bestaudio --extract-audio --audio-format mp3 --audio-quality 320k --embed-thumbnail --add-metadata'
fi


if [[ $link == */playlist?* ]]
then
    playlist="--yes-playlist"
    output='$EXTERNAL_STORAGE/YTDL/%(playlist_index)s.%(title)s.%(ext)s'
else
    playlist="--no-playlist"
    output='$EXTERNAL_STORAGE/YTDL/%(title)s.%(ext)s'
fi


yt-dlp $quiet -f $format --prefer-ffmpeg --output $output --no-mtime --no-post-overwrites --geo-bypass --ignore-errors $playlist $link

echo
echo
echo -e "${green}Done${e}"
